// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/location/location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationPayload) Reset() {
	*x = LocationPayload{}
	mi := &file_proto_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationPayload) ProtoMessage() {}

func (x *LocationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationPayload.ProtoReflect.Descriptor instead.
func (*LocationPayload) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationPayload) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LocationPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocationPayload) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LocationPayload) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *LocationPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_location_location_proto protoreflect.FileDescriptor

const file_proto_location_location_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/location/location.proto\x12\blocation\"\x8a\x01\n" +
	"\x0fLocationPayload\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2J\n" +
	"\x10LocationReceiver\x126\n" +
	"\x06Stream\x12\x19.location.LocationPayload\x1a\r.location.Ack(\x010\x01B\x1fZ\x1dgeoip-receiver/proto/locationb\x06proto3"

var (
	file_proto_location_location_proto_rawDescOnce sync.Once
	file_proto_location_location_proto_rawDescData []byte
)

func file_proto_location_location_proto_rawDescGZIP() []byte {
	file_proto_location_location_proto_rawDescOnce.Do(func() {
		file_proto_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)))
	})
	return file_proto_location_location_proto_rawDescData
}

var file_proto_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_location_location_proto_goTypes = []any{
	(*LocationPayload)(nil), // 0: location.LocationPayload
	(*Ack)(nil),             // 1: location.Ack
}
var file_proto_location_location_proto_depIdxs = []int32{
	0, // 0: location.LocationReceiver.Stream:input_type -> location.LocationPayload
	1, // 1: location.LocationReceiver.Stream:output_type -> location.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_location_location_proto_init() }
func file_proto_location_location_proto_init() {
	if File_proto_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_location_proto_rawDesc), len(file_proto_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_location_proto_goTypes,
		DependencyIndexes: file_proto_location_location_proto_depIdxs,
		MessageInfos:      file_proto_location_location_proto_msgTypes,
	}.Build()
	File_proto_location_location_proto = out.File
	file_proto_location_location_proto_goTypes = nil
	file_proto_location_location_proto_depIdxs = nil
}
