// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proto/location/location.proto

package location

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationReceiver_Stream_FullMethodName = "/location.LocationReceiver/Stream"
)

// LocationReceiverClient is the client API for LocationReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationReceiverClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationPayload, Ack], error)
}

type locationReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationReceiverClient(cc grpc.ClientConnInterface) LocationReceiverClient {
	return &locationReceiverClient{cc}
}

func (c *locationReceiverClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LocationPayload, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocationReceiver_ServiceDesc.Streams[0], LocationReceiver_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationPayload, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationReceiver_StreamClient = grpc.BidiStreamingClient[LocationPayload, Ack]

// LocationReceiverServer is the server API for LocationReceiver service.
// All implementations must embed UnimplementedLocationReceiverServer
// for forward compatibility.
type LocationReceiverServer interface {
	Stream(grpc.BidiStreamingServer[LocationPayload, Ack]) error
	mustEmbedUnimplementedLocationReceiverServer()
}

// UnimplementedLocationReceiverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationReceiverServer struct{}

func (UnimplementedLocationReceiverServer) Stream(grpc.BidiStreamingServer[LocationPayload, Ack]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedLocationReceiverServer) mustEmbedUnimplementedLocationReceiverServer() {}
func (UnimplementedLocationReceiverServer) testEmbeddedByValue()                          {}

// UnsafeLocationReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationReceiverServer will
// result in compilation errors.
type UnsafeLocationReceiverServer interface {
	mustEmbedUnimplementedLocationReceiverServer()
}

func RegisterLocationReceiverServer(s grpc.ServiceRegistrar, srv LocationReceiverServer) {
	// If the following call panics, it indicates UnimplementedLocationReceiverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationReceiver_ServiceDesc, srv)
}

func _LocationReceiver_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocationReceiverServer).Stream(&grpc.GenericServerStream[LocationPayload, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationReceiver_StreamServer = grpc.BidiStreamingServer[LocationPayload, Ack]

// LocationReceiver_ServiceDesc is the grpc.ServiceDesc for LocationReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.LocationReceiver",
	HandlerType: (*LocationReceiverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _LocationReceiver_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/location/location.proto",
}
