FROM golang:1.25-alpine

RUN apk add --no-cache protobuf

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && \
    go install github.com/air-verse/air@latest

ENV GOFLAGS=-mod=mod

WORKDIR /app

CMD ["sh", "-c", "\
    go mod download && \
    protoc \
        --go_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_out=. \
        --go-grpc_opt=paths=source_relative \
        proto/location/location.proto && \
    exec air -c .air.toml \
"]
